# sudo: enable
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
services:
    - docker
script:
  - npm run deploy
# notifications:
#   slack:
#     rooms:
#       - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
#     on_success: change
#     on_failure: always
