version: "3"
services:
    monitor:
        container_name: node-monitor
        restart: always
        build: .
        ports:
            - "4003:4003"
        links:
            - database
        depends_on:
            - database
        networks:
            - network-connect-middleware
    database:
        container_name: mongodb
        image: mongo
        restart: always
        volumes:
            - ~/Database:/data/db
        ports:
            - "27017:27017"
        networks:
            - network-connect-middleware
networks:
    network-connect-middleware:
        driver: bridge
