sudo: enable
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
cache:
  directories:
    - node_modules
script:
  - npm run lint 
notifications:
  slack: 
    rooms:
      - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
    on_success: change
    on_failure: always